name: Python ETL tests

on:
  pull_request:
    branches: [main]
    paths:
      - "modules/lambda_src/**"
  push:
    branches: [main]
    paths:
      - "modules/lambda_src/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r modules/lambda_src/requirements.txt

      - name: Run tests
        run: python3 -m pytest modules/lambda_src/ -v